/**
 * Template for the PostToolUse hook script (goal-post-tool.ts).
 * The generated script reads the tool event from stdin and
 * fires it to the daemon. Fire-and-forget — no output.
 */
export function generatePostToolHook(port: number = 17332): string {
	return `#!/usr/bin/env bun
// Auto-generated by codeforge goal install — do not edit manually.
// PostToolUse hook: records tool events to the goal daemon.

const PORT = process.env.CODEFORGE_GOAL_PORT ?? "${port}";
const BASE_URL = \`http://127.0.0.1:\${PORT}\`;
const TIMEOUT_MS = 5_000;

async function main(): Promise<void> {
	let input: unknown = {};
	try {
		const raw = await Bun.stdin.text();
		if (raw.trim()) {
			input = JSON.parse(raw);
		}
	} catch {
		return;
	}

	const cwd = process.cwd();
	const sessionId = process.env.CLAUDE_SESSION_ID ?? "";

	try {
		const controller = new AbortController();
		const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

		await fetch(\`\${BASE_URL}/events/tool\`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ cwd, sessionId, event: input }),
			signal: controller.signal,
		});

		clearTimeout(timer);
	} catch {
		// Fire-and-forget — ignore errors
	}
}

main();
`;
}
