/**
 * Template for the SessionStart hook script (goal-session-start.ts).
 * The generated script calls the daemon to check for an active goal
 * and injects goal context into Claude via additionalContext.
 */
export function generateSessionStartHook(port: number = 17332): string {
	return `#!/usr/bin/env bun
// Auto-generated by codeforge goal install — do not edit manually.
// SessionStart hook: rehydrates active goal context into Claude.

const PORT = process.env.CODEFORGE_GOAL_PORT ?? "${port}";
const BASE_URL = \`http://127.0.0.1:\${PORT}\`;
const TIMEOUT_MS = 5_000;

async function main(): Promise<void> {
	const cwd = process.cwd();

	try {
		const controller = new AbortController();
		const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

		const res = await fetch(
			\`\${BASE_URL}/goal/current?cwd=\${encodeURIComponent(cwd)}\`,
			{ signal: controller.signal },
		);

		clearTimeout(timer);

		if (res.ok) {
			const data = await res.json() as { goal?: { objective: string; status: string; currentCheckpoint: string; loopCount: number; maxLoops: number } };
			if (data.goal && data.goal.status === "active") {
				const g = data.goal;
				const context = [
					"[Goal Daemon] Active goal detected:",
					\`  Objective: \${g.objective}\`,
					\`  Checkpoint: \${g.currentCheckpoint}\`,
					\`  Progress: loop \${g.loopCount}/\${g.maxLoops}\`,
					"",
					"Read .claude/goal/plan.md for the full plan.",
					"Update .claude/goal/progress.md as you complete work.",
					"The Stop hook will verify your work before allowing you to stop.",
				].join("\\n");
				console.log(JSON.stringify({ additionalContext: context }));
				return;
			}
		}

		// No active goal or error — output nothing meaningful
		console.log(JSON.stringify({}));
	} catch {
		// Daemon unreachable — no-op
		console.log(JSON.stringify({}));
	}
}

main();
`;
}
