/**
 * Template for the Stop hook script (goal-stop.ts).
 * The generated script reads stdin, calls the daemon's evaluate-stop endpoint,
 * and outputs a hook decision.
 *
 * WHY fail-open (default to "allow" on ANY error): This hook runs inside Claude Code's
 * hook system. If it blocks, Claude cannot proceed. A crashed daemon, network timeout,
 * or malformed response must NEVER trap the user in a session they can't exit.
 * The cost of a false-allow is one unnecessary stop; the cost of a false-block is
 * a stuck session requiring force-kill.
 */
export function generateStopHook(port: number = 17332): string {
	return `#!/usr/bin/env bun
// Auto-generated by codeforge goal install — do not edit manually.
// Stop hook: calls daemon to evaluate whether the session should stop.

const PORT = process.env.CODEFORGE_GOAL_PORT ?? "${port}";
const BASE_URL = \`http://127.0.0.1:\${PORT}\`;
const TIMEOUT_MS = 30_000;

async function main(): Promise<void> {
	let input: unknown = {};
	try {
		const raw = await Bun.stdin.text();
		if (raw.trim()) {
			input = JSON.parse(raw);
		}
	} catch {
		// If stdin is empty or invalid, proceed with empty payload
	}

	const cwd = process.cwd();
	const sessionId = process.env.CLAUDE_SESSION_ID ?? "";

	try {
		const controller = new AbortController();
		const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

		const res = await fetch(\`\${BASE_URL}/goal/evaluate-stop\`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ cwd, sessionId, hookPayload: input }),
			signal: controller.signal,
		});

		clearTimeout(timer);

		if (res.ok) {
			const data = await res.json() as {
				decision: string;
				reason?: string;
				nextInstruction?: string;
				loopCount?: number;
				maxLoops?: number;
			};
			if (data.decision === "block") {
				let reason = data.reason ?? "Goal not yet complete";
				if (data.nextInstruction) {
					reason += "\\n\\nNext:\\n" + data.nextInstruction;
				}
				if (typeof data.loopCount === "number" && typeof data.maxLoops === "number") {
					reason += \` (loop \${data.loopCount}/\${data.maxLoops})\`;
				}
				console.log(JSON.stringify({ decision: "block", reason }));
				return;
			}
		}

		// Any non-block response (including errors) means allow
		console.log(JSON.stringify({ decision: "allow" }));
	} catch {
		// Daemon unreachable — never trap Claude
		console.log(JSON.stringify({ decision: "allow" }));
	}
}

main();
`;
}
