#!/usr/bin/env node

// generate-mounts.mjs — Reads .codeforge/mounts.json, generates docker-compose.codeforge.yml
// Runs on the HOST via initializeCommand. Must work on Windows, macOS, Linux.
// Node.js is always available (VS Code requires it).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const MOUNTS_FILE = ".codeforge/mounts.json";
const OUTPUT_FILE = ".devcontainer/docker-compose.codeforge.yml";

// When no mounts.json exists, generate an empty override so dockerComposeFile doesn't error
function generateEmptyOverride() {
	return [
		'# No custom volumes configured. Run "codeforge doctor --fix" inside the container.',
		"services:",
		"  codeforge: {}",
		"",
	].join("\n");
}

function sanitizeName(path) {
	return path.replace(/[^a-zA-Z0-9-]/g, "-").replace(/^-+|-+$/g, "");
}

function generateOverride(mounts) {
	const lines = [
		"# Auto-generated by CodeForge. Do not edit.",
		"# Source: .codeforge/mounts.json",
		"# Regenerate: codeforge doctor --fix --yes --only volumes",
		"services:",
		"  codeforge:",
		"    volumes:",
	];

	const volumeNames = [];

	for (const vol of mounts.volumes) {
		const volName = `codeforge-vol-${sanitizeName(vol.path)}`;
		// Use /workspaces/ prefix since that's the workspace mount target
		lines.push(`      - ${volName}:/workspaces/${vol.path}`);
		volumeNames.push(volName);
	}

	lines.push("");
	lines.push("volumes:");
	for (const name of volumeNames) {
		lines.push(`  ${name}:`);
	}
	lines.push("");

	return lines.join("\n");
}

// Main
try {
	let content;

	if (!existsSync(MOUNTS_FILE)) {
		content = generateEmptyOverride();
	} else {
		const raw = readFileSync(MOUNTS_FILE, "utf-8");
		const mounts = JSON.parse(raw);

		if (!mounts.volumes || mounts.volumes.length === 0) {
			content = generateEmptyOverride();
		} else {
			content = generateOverride(mounts);
		}
	}

	// Ensure output directory exists
	const outputDir = dirname(OUTPUT_FILE);
	if (!existsSync(outputDir)) {
		mkdirSync(outputDir, { recursive: true });
	}

	writeFileSync(OUTPUT_FILE, content, "utf-8");
	console.log(`[CodeForge] Generated ${OUTPUT_FILE}`);
} catch (err) {
	// Don't fail the container build if mount generation fails
	console.warn(`[CodeForge] Warning: mount generation failed: ${err.message}`);
	// Write empty override as fallback
	try {
		writeFileSync(OUTPUT_FILE, generateEmptyOverride(), "utf-8");
	} catch {}
}
