#!/usr/bin/env node

// generate-compose.mjs — Reads .codeforge/mounts.json and .codeforge/secrets/,
// generates docker-compose.codeforge.yml with volumes and secrets.
// Runs on the HOST via initializeCommand. Must work on Windows, macOS, Linux.
// Node.js is always available (VS Code requires it).

import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const MOUNTS_FILE = ".codeforge/mounts.json";
const SECRETS_DIR = ".codeforge/secrets";
const OUTPUT_FILE = ".devcontainer/docker-compose.codeforge.yml";

function sanitizeName(path) {
	return path.replace(/[^a-zA-Z0-9-]/g, "-").replace(/^-+|-+$/g, "");
}

function discoverSecrets() {
	if (!existsSync(SECRETS_DIR)) {
		return [];
	}
	try {
		return readdirSync(SECRETS_DIR)
			.filter((name) => {
				const fullPath = join(SECRETS_DIR, name);
				return statSync(fullPath).isFile() && !name.startsWith(".");
			})
			.sort();
	} catch {
		return [];
	}
}

function loadMounts() {
	if (!existsSync(MOUNTS_FILE)) {
		return [];
	}
	try {
		const raw = readFileSync(MOUNTS_FILE, "utf-8");
		const mounts = JSON.parse(raw);
		return mounts.volumes || [];
	} catch {
		return [];
	}
}

function generateCompose(mounts, secrets) {
	const lines = [
		"# Auto-generated by CodeForge. Do not edit.",
		"# Sources: .codeforge/mounts.json, .codeforge/secrets/",
		"# Regenerate: codeforge doctor --fix --yes --only volumes",
	];

	const hasVolumes = mounts.length > 0;
	const hasSecrets = secrets.length > 0;

	lines.push("services:");
	lines.push("  codeforge:");

	if (hasVolumes) {
		lines.push("    volumes:");
		for (const vol of mounts) {
			const volName = `codeforge-vol-${sanitizeName(vol.path)}`;
			lines.push(`      - ${volName}:/workspaces/${vol.path}`);
		}
	}

	if (hasSecrets) {
		lines.push("    secrets:");
		for (const name of secrets) {
			lines.push(`      - ${name}`);
		}
	}

	if (!hasVolumes && !hasSecrets) {
		lines[lines.length - 1] = "  codeforge: {}";
	}

	if (hasVolumes) {
		lines.push("");
		lines.push("volumes:");
		for (const vol of mounts) {
			const volName = `codeforge-vol-${sanitizeName(vol.path)}`;
			lines.push(`  ${volName}:`);
		}
	}

	if (hasSecrets) {
		lines.push("");
		lines.push("secrets:");
		for (const name of secrets) {
			if (!/^[a-zA-Z0-9_-]+$/.test(name)) {
				console.error(`[CodeForge] Invalid secret name: ${name}`);
				process.exit(1);
			}
			lines.push(`  ${name}:`);
			lines.push(`    file: ../.codeforge/secrets/${name}`);
		}
	}

	lines.push("");
	return lines.join("\n");
}

// Main
try {
	const mounts = loadMounts();
	const secrets = discoverSecrets();
	const content = generateCompose(mounts, secrets);

	const outputDir = dirname(OUTPUT_FILE);
	if (!existsSync(outputDir)) {
		mkdirSync(outputDir, { recursive: true });
	}

	writeFileSync(OUTPUT_FILE, content, "utf-8");

	const parts = [];
	if (mounts.length > 0) parts.push(`${mounts.length} volume(s)`);
	if (secrets.length > 0) parts.push(`${secrets.length} secret(s)`);
	const summary = parts.length > 0 ? parts.join(", ") : "empty override";
	console.log(`[CodeForge] Generated ${OUTPUT_FILE} (${summary})`);
} catch (err) {
	console.warn(
		`[CodeForge] Warning: compose generation failed: ${err.message}`,
	);
	try {
		const fallback = [
			"# Compose generation failed. Empty override.",
			"services:",
			"  codeforge: {}",
			"",
		].join("\n");
		writeFileSync(OUTPUT_FILE, fallback, "utf-8");
	} catch (innerErr) {
		console.error(
			`[CodeForge] Fallback compose generation failed: ${innerErr.message}`,
		);
		process.exit(1);
	}
}
